source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASVideoPlayer_Example', :exclusive => true do
  pod "ASVideoPlayer", :path => "../"
end

target 'ASVideoPlayer_Tests', :exclusive => true do
  pod "ASVideoPlayer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'SVProgressHUD'
end
